version: 2
updates:
  - package-ecosystem: "npm" ## for npm and yarn things
    directories: "/**"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "docker"
    directory: "/Docker/101/app"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
